server:
  port: 8080

spring:
  application:
    name: "DoctorOffice"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://database:5432/project3}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:nopass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    resources:
      add-mappings: false

# Kafka broker list used by KafkaProducerConfig & KafkaStreamsConfig
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker1:9092,broker2:9092,broker3:9092}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
